# 넘파이의 ndarray 사용

In [2]:
import numpy as np

a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
a.shape #객체 형태 (튜플)

(3,)

In [4]:
a.ndim #객체 내부 차원

1

In [5]:
a.dtype #객체 내부 자료형

dtype('int32')

In [6]:
a.itemsize #객체 내부 자료형이 차지하는 메모리 크기

4

In [7]:
a.size #객체 배열의 크기 (항목의 수)

3

# 넘파이와 데이터형

In [8]:
a=np.array([1,2,3],dtype='int32') #정수는 8,16,32,64 비트 자료형도 사용 가능
b=np.array([1,2,3],dtype='int64')
a.dtype

dtype('int32')

In [9]:
b.dtype

dtype('int64')

In [10]:
c=a+b #자동으로 상위버전으로 호환
c.dtype

dtype('int64')

# ndarray 리스트 형식의 데이터로 ([array])이런식으로 넣어줘야함.
### 잘못된 예) np.array(1,2,3,4)

# 넘파이의 ndarray는 서로 다른 자료형을 가질 수 없음.
### np.array([1,'two',3,4]) >> 나머지 1,3,4는 형변환이 일어나 문자형으로 바뀜

In [11]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [12]:
a=np.array(1,2,3,4)

ValueError: only 2 non-keyword arguments accepted

In [13]:
a = np.array([1, 'two', 3, 4], dtype=np.int32) #인트형으로 불가능
a

ValueError: invalid literal for int() with base 10: 'two'

In [14]:
a=np.array(['1','two','3','4']) #자료형은 통일
a

array(['1', 'two', '3', '4'], dtype='<U3')

# 데이터타입을 지정하는 두가지 방법

In [15]:
np.array([1,2,3,4],dtype='int32')

array([1, 2, 3, 4])

In [16]:
np.array([1,2,3,4],dtype=np.int32)

array([1, 2, 3, 4])

# LAB 11-1

In [17]:
a=np.array([0,1,2,3,4,5,6,7,8,9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
b=np.array(list(range(0,10))) #시험 문제
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
c=np.array([i for i in range(0,10) if i%2==0],dtype=np.int64) #시험 문제
c

array([0, 2, 4, 6, 8], dtype=int64)

In [20]:
print("c.shape = ",c.shape,end='')

c.shape =  (5,)

In [21]:
print("c.ndim = ",c.ndim,end='')

c.ndim =  1

In [22]:
print("c.dtype = ",c.dtype,end='')

c.dtype =  int64

In [23]:
print("c.size = ",c.size,end='')

c.size =  5

In [24]:
print("c.itemsize = ",c.itemsize,end='')

c.itemsize =  8

# ndarray  method()

### max() min() mean()

In [25]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [26]:
a.max()

3

In [27]:
a.min()

1

In [28]:
a.mean()

2.0

### flatten()

In [29]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

### append() 

In [31]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [32]:
b=np.array([[4,5,6],[7,8,9]])
b

array([[4, 5, 6],
       [7, 8, 9]])

In [33]:
np.append(a,b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.append([a],b,axis=0) #차원을 유지한채 넣어주고 싶다.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### rand()

In [36]:
np.random.rand(3,3) # 랜덤으로 3,3 배열을 만듬.

array([[0.83881901, 0.38536356, 0.4797209 ],
       [0.38264825, 0.68736731, 0.58649311],
       [0.81017052, 0.24227813, 0.44004828]])

### randint()

In [37]:
np.random.randint(0,10,size=10)

array([3, 9, 8, 5, 2, 2, 5, 0, 5, 7])

# LAB11-2

In [38]:
a=np.array([23,45,67,7,2,30,34,82])#LAB11-2-1
print(f'a = array({a})')

a = array([23 45 67  7  2 30 34 82])


In [79]:
print(f'최댓값 : {a.max()}')#LAB11-2-2
print(f'최솟값 : {a.min()}')
print(f'평균 : {a.mean()}')

최댓값 : 82
최솟값 : 2
평균 : 36.25


In [59]:
import random
b=np.random.randint(0,10,size=10)
c=random.randint(0,10)
print(f'c = {c}')
print(f'b = {b}')
print(f'최댓값 : {b.max()}')#LAB11-2-3
print(f'최솟값 : {b.min()}')
print(f'평균 : {b.mean()}')

c = 10
b = [6 7 3 9 8 0 6 4 9 5]
최댓값 : 9
최솟값 : 0
평균 : 5.7


In [85]:
c=np.append(a,b)#LAB11-2-4
print(f'c = {c}')

c = [23 45 67  7  2 30 34 82 25 27 40 10 13 71 37 71 63 75]


# ndarray의 연산

In [60]:
a = np.array([1, 2, 3])   # 1, 2, 3 원소를 가지는 1차원 ndarray
b = np.array([4, 5, 6])   # 4, 5, 6 원소를 가지는 1차원 ndarray
c = a + b                 # 1차원 ndarray의 덧셈
c

array([5, 7, 9])

### shape이 다를 경우(에러)

In [61]:
a = np.array([1, 2])     # 2개의 원소를 가지는 1차원 배열 : (2,) shape
b = np.array([4, 5, 6])  # 3개의 원소를 가지는 1차원 배열 : (3,) shape
c = a + b

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

### 2차원 ndarray의 사칙연산

In [62]:
a=np.array([[1,2],[3,4]])
b=np.array([[10,20],[30,40]])
a

array([[1, 2],
       [3, 4]])

In [63]:
b

array([[10, 20],
       [30, 40]])

In [64]:
a+b

array([[11, 22],
       [33, 44]])

In [65]:
a-b

array([[ -9, -18],
       [-27, -36]])

In [66]:
a*b

array([[ 10,  40],
       [ 90, 160]])

In [67]:
a/b

array([[0.1, 0.1],
       [0.1, 0.1]])

# 행렬의 곱(matmaul(),@) *사칙연산이랑 다름

In [68]:
np.matmul(a,b)

array([[ 70, 100],
       [150, 220]])

In [69]:
a@b

array([[ 70, 100],
       [150, 220]])

In [70]:
a[0,0] * b[0,0] + a[0,1] * b[1,0]

70

In [71]:
a[0,0] * b[0,1] + a[0,1] * b[1,1]

100

In [72]:
a[1,0] * b[0,0] + a[1,1] * b[1,0]

150

In [73]:
a[1,0] * b[0,1] + a[1,1] * b[1,1]

220

# 단위 행렬에 대한 행렬 곱

In [74]:
a=[[1,2],[3,4]]
b=[[1,0],[0,1]]
np.matmul(a,b)

array([[1, 2],
       [3, 4]])

In [75]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,0],[0,1]])
a@b

array([[1, 2],
       [3, 4]])

# ndarray의 덧셈 뺄셈 곱셈 나눗셈 제곱 연산

In [76]:
a=np.array([[1,2],[3,4]])
a+1

array([[2, 3],
       [4, 5]])

In [77]:
a-1

array([[0, 1],
       [2, 3]])

In [78]:
a*100

array([[100, 200],
       [300, 400]])

In [79]:
a/100

array([[0.01, 0.02],
       [0.03, 0.04]])

In [80]:
a**2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

# LAB11-3

In [81]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])# LAB11-3-1
b=np.array([[2,2,2],[2,2,2],[2,2,2]])

In [82]:
a+b

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [83]:
a-b

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [84]:
a*b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [85]:
a@b #np.matmul(a,b)

array([[12, 12, 12],
       [30, 30, 30],
       [48, 48, 48]])

In [86]:
a**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

# ndarray의 생성

In [87]:
np.zeros((2,3)) #각 요소가 인 nxm 행렬

array([[0., 0., 0.],
       [0., 0., 0.]])

In [88]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [89]:
np.full((2,3),100)

array([[100, 100, 100],
       [100, 100, 100]])

In [90]:
#주의 
np.full(2,3) #이거는 1차원 2개로 이루어져있는 행렬을 3으로 채워라.

array([3, 3])

In [91]:
np.eye(3) #정방행렬에 대해서만 생성이 가능하다(단위행렬)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [92]:
np.random.random((2,3)) #난수를 생성해서 2x3행렬을 만듬

array([[0.2440679 , 0.38044658, 0.79617735],
       [0.30164093, 0.47346584, 0.89112101]])

# arrange()함수를 이용한 배열

In [93]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
np.arange(0,10,2)
np.array([i for i in range(0,10) if i%2==0])

array([0, 2, 4, 6, 8])

In [95]:
np.arange(0,10,3)
np.array([i for i in range(0,10) if i%3==0])

array([0, 3, 6, 9])

In [96]:
np.arange(0.0,1.0,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

# linespace()를 이용한 배열

In [97]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [98]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

# LAB 11-4

In [99]:
#LAB 11-4-1
a1 = np.full((3,3),2)
print(f'a1 = {a1}')

a1 = [[2 2 2]
 [2 2 2]
 [2 2 2]]


In [100]:
#LAB 11-4-2
a2=np.arange(1,13)
print(f'a2 = {a2}')

a2 = [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [101]:
#LAB 11-4-3
a3=np.arange(3,50,3)
print(f'a3 = {a3}')

a3 = [ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]


In [102]:
#LAB 11-4-4
a4=np.linspace(0,20,5)
print(f'a4 = {a4}')

a4 = [ 0.  5. 10. 15. 20.]


# reshape() 

In [103]:
np.arange(0,10).reshape(2,5) # 1부터 10까지 1차원배열을 2by5배열로 만들어라.

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [104]:
np.arange(0,10).reshape(5,2) # 1부터 10까지 1차원배열을 5by2배열로 만들어라.

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [161]:
np.arange(0,10).reshape(3,3) # 쌍이 맞지않는 값으로 reshape하려고 하면 오류가 난다.

ValueError: cannot reshape array of size 10 into shape (3,3)

# 다른 차원으로의 reshape()

In [106]:
np.arange(0,24).reshape(4,3,2) # 3by2행렬이 4개가 있다는 것. 3차원 배열

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [107]:
a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [108]:
np.transpose(a) #행렬을 바꿈.

array([[0, 2, 4],
       [1, 3, 5]])

In [109]:
a.transpose()

array([[0, 2, 4],
       [1, 3, 5]])

# LAB 11-5

In [172]:
a1=np.arange(1,13).reshape(2,6)
print(f'a1 = {a1}')

a1 = [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [178]:
a2=np.arange(1,31).reshape(3,10)
print(f'a2 = {a2}')

a2 = [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [179]:
a3=a2.reshape(6,5)
print(f'a3 = {a3}')

a3 = [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [183]:
a4=np.transpose(a3)
print(f'a4 = {a4}')

a4 = [[ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]
 [ 5 10 15 20 25 30]]


# 다차원 배열의 축 (axis=0, axis=1)

In [185]:
a=np.arange(0,6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [186]:
a.sum() #모든 원소들이 다 sum()

15

In [187]:
a.sum(axis=0)

array([6, 9])

In [188]:
a.sum(axis=1)

array([1, 5, 9])

In [189]:
a.max(axis=0)

array([4, 5])

In [190]:
a.max(axis=1)

array([1, 3, 5])

In [191]:
a.min(axis=0)

array([0, 1])

In [192]:
a.min(axis=1)

array([0, 2, 4])

# ndarray의 insert()

In [194]:
a=np.array([1,3,4])
np.insert(a,1,2)

array([1, 2, 3, 4])

In [197]:
a=np.array([[1,1],[2,2],[3,3]])
np.insert(a,1,4,axis=0)

array([[1, 1],
       [4, 4],
       [2, 2],
       [3, 3]])

In [198]:
np.insert(a,1,4,axis=1)

array([[1, 4, 1],
       [2, 4, 2],
       [3, 4, 3]])

# LAB 11-6

In [203]:
a=np.random.randint(1,101,15).reshape(3,5)
print(f'a = {a}')

a = [[90 99  6 34 89]
 [71  4 82 72 85]
 [57 14 82 18  7]]


In [206]:
print(f'a의 열방향 최댓값 : {a.max(axis=0)}')
print(f'a의 열방향 최솟값 : {a.min(axis=0)}')
print(f'a의 열방향 평균 : {a.mean(axis=0)}')

a의 열방향 최댓값 : [90 99 82 72 89]
a의 열방향 최솟값 : [57  4  6 18  7]
a의 열방향 평균 : [72.66666667 39.         56.66666667 41.33333333 60.33333333]


In [207]:
print(f'a의 행방향 최댓값 : {a.max(axis=1)}')
print(f'a의 행방향 최솟값 : {a.min(axis=1)}')
print(f'a의 행방향 평균 : {a.mean(axis=1)}')

a의 행방향 최댓값 : [99 85 82]
a의 행방향 최솟값 : [6 4 7]
a의 행방향 평균 : [63.6 62.8 35.6]


# 1차원 배열의 인덱싱 / 슬라이싱

In [208]:
a = np.array([1, 2, 3])
print(a[0], a[1], a[2])

1 2 3


In [209]:
print(a[-1], a[-2], a[-3]) #음수로 인덱싱 3(-1) 2(-2) 1(-3)

3 2 1


In [212]:
a=np.array([1,2,3,4,5])
print(a[np.array([0,1])])
print(a[np.array([0,1,2])])
print(a[np.array([0,1,3])])
print(a[np.array([1,1,1,1])])

[1 2]
[1 2 3]
[1 2 4]
[2 2 2 2]


In [216]:
a[3,4] #3은 axis = 0 4는 axis = 1로 해석

IndexError: too many indices for array

# 슬라이싱

In [217]:
a_list=[10,20,30,40,50,60,70,80]
a_list[1:5]

[20, 30, 40, 50]

In [218]:
a=np.array([10,20,30,40,50,60,70,80])
a[1:5]

array([20, 30, 40, 50])

In [219]:
a[1:]

array([20, 30, 40, 50, 60, 70, 80])

In [ ]:
a[:]

In [220]:
a[::2]#3번째 2는 스텝값

array([10, 30, 50, 70])

In [221]:
a[::-1]#리버싱 음수 스텝값

array([80, 70, 60, 50, 40, 30, 20, 10])

# LAB 11-7

In [228]:
a=np.arange(1,11)
b=a[1:8:2]
print(f'a = {a}')
print(f'b = {b}')

a = [ 1  2  3  4  5  6  7  8  9 10]
b = [2 4 6 8]


In [229]:
b=a[5:]
print(f'b = {b}')

b = [ 6  7  8  9 10]


In [230]:
c=a[6:]
print(f'c = {c}')

c = [ 7  8  9 10]


In [233]:
d=a[:3]
print(f'd = {d}')

d = [1 2 3]


In [235]:
e=a[::2]
print(f'e = {e}')

e = [1 3 5 7 9]


In [238]:
f=a[-1::-2]
print(f'f = {f}')

f = [10  8  6  4  2]


# 2차원 배열의 인덱싱

In [239]:
a = np.arange(0, 6).reshape(3, 2)
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [240]:
print(a[0])

[0 1]


In [241]:
print(a[0, 0])#행,열 이런형식 0행 0열

0


In [242]:
print(a[0, 1])#행,열 이런형식 0행 1열

1


In [243]:
print(a[0, 2]) #범위를 벗어났으니 에러.

IndexError: index 2 is out of bounds for axis 1 with size 2

# 3차원 배열의 인덱싱

In [249]:
a=np.arange(0,24).reshape(4,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [248]:
print(a[1,2,1])

11


In [250]:
a=np.arange(0,24).reshape(4,3,2)
a[0]

array([[0, 1],
       [2, 3],
       [4, 5]])

In [251]:
a[0,0]

array([0, 1])

In [252]:
a[0,1]

array([2, 3])

In [253]:
a[0,2]

array([4, 5])

In [257]:
np.concatenate((a[0,0],a[0,2]),axis=0)

array([0, 1, 4, 5])

# LAB 11-8

In [367]:
# LAB 11-8
a=np.arange(0,24).reshape(4,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [369]:
print("index\telement")
for i in np.ndindex(4,3,2):
    print(f'{i}\t{a[i]}')

index	element
(0, 0, 0)	0
(0, 0, 1)	1
(0, 1, 0)	2
(0, 1, 1)	3
(0, 2, 0)	4
(0, 2, 1)	5
(1, 0, 0)	6
(1, 0, 1)	7
(1, 1, 0)	8
(1, 1, 1)	9
(1, 2, 0)	10
(1, 2, 1)	11
(2, 0, 0)	12
(2, 0, 1)	13
(2, 1, 0)	14
(2, 1, 1)	15
(2, 2, 0)	16
(2, 2, 1)	17
(3, 0, 0)	18
(3, 0, 1)	19
(3, 1, 0)	20
(3, 1, 1)	21
(3, 2, 0)	22
(3, 2, 1)	23


In [347]:
np.concatenate((a[0,0],a[1,0]),axis=0)# LAB 11-8-2-1

array([0, 1, 6, 7])

In [348]:
np.concatenate((a[0,0],a[2,1]),axis=0)# LAB 11-8-2-2

array([ 0,  1, 14, 15])

In [349]:
np.concatenate((a[0],a[1]),axis=0)# LAB 11-8-2-3

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [351]:
np.concatenate((a[0],a[1]),axis=1)# LAB 11-8-2-4

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

# 2차원 배열의 슬라이싱

In [276]:
a=np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [277]:
a=np.arange(0,9).reshape(3,3)
print(a[0])

[0 1 2]


In [278]:
print(a[0,:])

[0 1 2]


In [280]:
print(a[:,0])

[0 3 6]


In [282]:
print(a[0,0:2])

[0 1]


In [283]:
print(a[0, :2])

[0 1]


In [284]:
print(a[0:2, 0:2]) #2by2배열

[[0 1]
 [3 4]]


In [285]:
print(a[:2, :2]) #2by2배열

[[0 1]
 [3 4]]


In [286]:
print(a[1:,1:])

[[4 5]
 [7 8]]


In [287]:
print(a[1,1:])

[4 5]


In [288]:
a[1,1:].shape

(2,)

In [289]:
a[1:2,1:].shape

(1, 2)

# LAB 11-9

In [353]:
#11-9-1
a=np.arange(0,16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [354]:
#LAB11-9-1
b=a[:,1]
print(f'b = {b}')

b = [ 1  5  9 13]


In [355]:
#LAB11-9-1
c=a[2,1:]
print(f'c = {c}')

c = [ 9 10 11]


In [356]:
#LAB11-9-1
d=a[:2,:2]
print(f'd = [{d[0]}{d[1]}]')

d = [[0 1][4 5]]


In [357]:
#LAB11-9-1
e=a[1:3,1:3]
print(f'e = [{e[0]}{e[1]}]')

e = [[5 6][ 9 10]]


In [358]:
#LAB11-9-2
f=a[:2,:3]
print(f'f = {f.flatten()}')

f = [0 1 2 4 5 6]


In [359]:
#LAB11-9-2
g=a[2:,:]
print(f'g = {g.flatten()}')

g = [ 8  9 10 11 12 13 14 15]


In [364]:
#LAB11-9-2
# a[1,1:]=[5,6,7]
# a[3,1:]=[13,14,15]
h=np.concatenate((a[1,1:],a[3,1:]),axis=0)
print(f'h = {h}')

h = [ 5  6  7 13 14 15]


# 선형 방정식 풀이, 행렬식

In [322]:
a=np.array([[2,3],[1,-2]])
b=np.array([1,4])
x=np.linalg.solve(a,b)
print(x)

[ 2. -1.]


In [323]:
b = np.array([[1, 2], [3, -6]])
np.linalg.det(b)

-12.0

In [324]:
b = np.array([[1, 2], [1, 2]])
np.linalg.det(b)

0.0

# LAB 11-10

In [333]:
a=np.array([[1,1,-1],[2,-1,3],[1,2,1]])
b=np.array([0,9,8])
x=np.linalg.solve(a,b)
print(f'x = {x[0]:0.1f}, y = {x[1]}, z = {x[2]:0.1f}')

x = 1.0, y = 2.0, z = 3.0


In [335]:
c=np.linalg.det(a)
print(f'det(A) = {c:0.1f}')

det(A) = -11.0
